'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { ReactNode } from 'react';
import { Provider } from 'react-redux';
import { store } from '@/redux/store';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: 'RTK-Query Upload File',
// 	description: 'Generated by create next app'
// };

export default function RootLayout({
	children
}: {
	children: Readonly<ReactNode>;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Provider store={store}>{children}</Provider>
			</body>
		</html>
	);
}
